### ISSUE TITLE
Format Version

### ISSUE THREAD

**Issue by Nghi93** [Barzahlen/camt_parser#11]
Hey,

right now there is only one supported version for each camt format e.g. camt.054.001.04.
But I need to parse camt.054.001.02 formats.
How about to structure the Base class like this: CamtParser::Format054::V001::V04::Base
in order to support different versions?

I can provide a Pull request.

**Comment by tobischo** [comment]
Is the difference that significant between the two formats that reflecting it on a class/module level even makes sense?
Currently camt parser is just a wrapper from XML to objects with methods for xml fields that may or may not hold values.

**Comment by Nghi93** [comment]
I thought so too.
Then at least the camt_parser/lib/camt_parser/xml.rb case statement should be weaken
to allow other versions.
```ruby
      case namespaces
      when 'urn:iso:std:iso:20022:tech:xsd:camt.052.001.02'
        return CamtParser::Format052::Base.new(doc.xpath('Document'))
      when 'urn:iso:std:iso:20022:tech:xsd:camt.053.001.02'
        return CamtParser::Format053::Base.new(doc.xpath('Document'))
      when 'urn:iso:std:iso:20022:tech:xsd:camt.054.001.04'
        return CamtParser::Format054::Base.new(doc.xpath('Document'))
      else
        raise CamtParser::Errors::UnsupportedNamespaceError, namespaces
      end
```

**Comment by tobischo** [comment]
I am fine with that. Something similar is actually being added in https://github.com/Barzahlen/camt_parser/pull/8 for CAMT053

**Comment by Nghi93** [comment]
I have submitted a pull request #12

**Comment by tobischo** [comment]
I have responded on your pull request.
